### ISSUE TITLE
Rearfire as useless weapon with target_give

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#10]
Another bug related to all rearfire weapons. For example: When you add mines to the player via target_give, they appear as a weapon with the model, but when shot, wastes them.
https://youtu.be/mbQ9GlIxRhE

**Comment by P3rlE** [comment]
Tried it by myself. It only happens when you give the rear fire weapons on spawn. When you give them triggered by a button or something it works perfect.
