### ISSUE TITLE
Widescreen Support (4:3 mode in 16:9 bug)

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#16]
![изображение](https://user-images.githubusercontent.com/91471199/150502149-c530475f-0a38-4392-b0fb-a958b237dd66.png)

**Comment by zturtleman** [comment]
Suggestion: Revert danial_dm's widescreen support that alters every draw call by free hand to "look right" at only 16:9 and instead use my cgame-wide (not per-draw call) aspect correct at any and every aspect widescreen support from Spearmint, ported back to ioquake3.
- web page: https://clover.moe/flexible-hud-for-ioq3/
- source code: https://github.com/zturtleman/ioq3/compare/master...flexible_hud
(suggest leaving out the pointless cvars for scaling and stuff)
