### ISSUE TITLE
Telefrag Gun doesn't work correctly

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#37]
When shooting a car with Telefrag Gun, either I teleport or nothing happens or teleports from above..

**Comment by P3rlE** [comment]
I played several rounds today. It never happend to me. :-)

**Comment by insellium** [comment]
> I played several rounds today. It never happend to me. :-)

To my surprise, I also teleported without error several times in a row (except for when I fall through the texture down). Strange. I probably meant those moments when hitting the car, it did not count and the teleport did not happen.
