### ISSUE TITLE
Last commits issues: Flattened numbers & "Wrong way" is not on center

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#38]
![изображение](https://user-images.githubusercontent.com/91471199/157188601-7b3f124e-f925-479c-9d50-e692911f7e2c.png)
![изображение](https://user-images.githubusercontent.com/91471199/157188633-6e7c37dd-d5e2-464f-b266-091077ba4fac.png)

**Comment by zturtleman** [comment]
I fixed "wrong way" in https://github.com/Q3Rally-Team/q3rally/commit/2010b17a0f255d6072b00aed7a87d3e2e4b1fe69. I don't understand what flattened numbers means.
