### ISSUE TITLE
"info_player_intermission" camera angle bug

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#42]
When I use info_notnull and bezierdir to change the camera position of info_player_intermission, when the scoreboard appears, the camera's view is reset by default.
![изображение](https://github.com/Q3Rally-Team/q3rally/assets/91471199/01b1197b-d0a6-4b09-b8b5-6c2013bfa235)
![изображение](https://github.com/Q3Rally-Team/q3rally/assets/91471199/80a371dd-ae01-40c3-9d7e-efb1e3b06976)
![изображение](https://github.com/Q3Rally-Team/q3rally/assets/91471199/2b620579-797c-41f5-9550-e5526948afee)

**Comment by zturtleman** [comment]
This should be fixed by https://github.com/Q3Rally-Team/q3rally/compare/d1a077258670...528645fe86fb.

**Comment by insellium** [comment]
> This should be fixed by [d1a0772...528645f](https://github.com/Q3Rally-Team/q3rally/compare/d1a077258670...528645fe86fb).

It works!
