### ISSUE TITLE
Usable server map rotation configs

### ISSUE THREAD

**Issue by zturtleman** [Q3Rally-Team/q3rally#45]
@insellium can https://github.com/Q3Rally-Team/q3rally/commit/47893b81f99bd28aeef390f0f3f9bc598c6c8dee be a separate server_example.cfg and leave the original q3r_*.cfg alone as just the gametype / map rotation? That way a server can easily switch gametype / map rotation (either in server config or while the server is running) and not forced to use whatever stuff is in the example config.

default.cfg and q3r_*.cfg should be in pak0.pk3. I think server_example.cfg would be more documentation than part of the game. Though I'm not sure where else to put it besides baseq3r right now.

**Comment by insellium** [comment]
Sure. That's easy.

**Comment by insellium** [comment]
i mean...i can create server_example.cfg

**Comment by insellium** [comment]
I did it in https://github.com/Q3Rally-Team/q3rally/commit/d69613a527811c727bbc2d5cd839fb721ec5fca4
