### ISSUE TITLE
The "Impressive" Medal appears all too often. 

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#6]
When firing the Railgun, the message "Impressive" appears all the time. This same message appears all the time. As far as I remember, in the original Quake 3, this medal appeared only occasionally, not all the time when the shot was fired.

**Comment by insellium** [comment]
Fixed in https://github.com/Q3Rally-Team/q3rally/commit/aa25dbacbcaecce93b4153054333f4e3f5bd0fc7

**Comment by insellium** [comment]
The medal as I see it is still on crutches and needs to be finalized.

**Comment by P3rlE** [comment]
The medal looks good in my opinion.
