### ISSUE TITLE
Gamepad & Steering wheel support (XInput)

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#61]
My gamepads (8BitDo Pro 2 and Xbox Wireless Controller) doesn't work. 
The same goes for the steering wheel: https://www.youtube.com/watch?v=5f5ahdFQlQw

**Comment by zturtleman** [comment]
Did you enable joystick in the menu? (config -> controls -> joystick). Or from console: `in_joystick 1; in_restart`. `print in_availableJoysticks` should show if any joysticks are found.

**Comment by insellium** [comment]
![изображение](https://github.com/Q3Rally-Team/q3rally/assets/91471199/11b32fd9-d95e-41e3-804a-aedfcaa799a3)

Gamepad is works! Thanks for help!
