### ISSUE TITLE
Fix gametype: Time Trial

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#62]
/g_gametype 2 invokes "time trial" game mode, but it works like deathmatch mode. Btw Time Trial is hidden game type.
![image](https://github.com/Q3Rally-Team/q3rally/assets/91471199/b2891a2c-968a-42b9-8e66-c1df8e611c51)
![image](https://github.com/Q3Rally-Team/q3rally/assets/91471199/1f85f028-3d54-4098-a524-2331a5c8c7c8)

**Comment by P3rlE** [comment]
Time Trial is a never finished, planned gametype. I don´t plan to reactivate it. Most of the code is already removed.
