### ISSUE TITLE
Wrong hud position of power-ups & flag in various screen aspect ratio

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#65]
**16:9**
![q3rally x86_64_kPh2GMV1Bi](https://github.com/Q3Rally-Team/q3rally/assets/91471199/fe0e87fb-cb80-4073-8cdb-a1bac05ac327)

**4:3**
![q3rally x86_64_zWxGLINBEt](https://github.com/Q3Rally-Team/q3rally/assets/91471199/7475d280-5e28-412d-bdce-ec339419903a)

**5:4**
![q3rally x86_64_jzcQQ6rh4k](https://github.com/Q3Rally-Team/q3rally/assets/91471199/f3228af6-3c51-43f4-97d7-d281d379191e)

**Comment by zturtleman** [comment]
I think the flag is fine. The power up is fixed in https://github.com/Q3Rally-Team/q3rally/compare/67c0b325ec50695b05f09ab72e18198da7014289...d8dcb28d04c2871715ff4e57a0c5170f14b09746.
