### ISSUE TITLE
System message in CTF 

### ISSUE THREAD

**Issue by insellium** [Q3Rally-Team/q3rally#8]
When shooting in teammate with Friendly Fire turned off, a system message pops up, which can spam the entire console window if you keep firing.
https://youtu.be/6_0AvajvXlU

**Comment by P3rlE** [comment]
It has nothing to do with friendly fire on or off. The message comes on every shoot on a teaammate in ctf.

**Comment by P3rlE** [comment]
Fixed. :-)
